@noteId = 683eb9f9073bb0a65e58d1fd
@tokenlendy = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkxlbmR5IiwiaWQiOiI2ODM4NjU1ODUzM2M5YWQ4NWI0NTA2NDciLCJpYXQiOjE3NDg1MjY0Mzl9.JuyNYwGvu3cy8g3716U96pkqV3rKJSTFEVJDo3TKIdo

DELETE http://localhost:3003/api/blogs/{{noteId}}
Authorization: Bearer {{tokenlendy}}