POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Post de prueba",
    "author": "Lendy Sanchez",
    "url": "http://alguna_direccion.algun_domino",
    "likes": 100
}